### ISSUE TITLE
mailto: links should not open in a new window.

### ISSUE THREAD

**Issue by ndbroadbent** [mxstbr/sharing#32] opened 2016-08-02 20:16 UTC
It opens a new empty web browser tab even when the links are handled by the OS (e.g. native mail client).

**Comment by billyquick** [comment] 2016-08-02 21:19
Hey @ndbroadbent, what web browsers have you tried using? Some browsers support defaulting pop-up windows to open a new tab and some do not.

**Comment by ndbroadbent** [comment] 2016-08-02 21:55
Hi, this happens for me on OS X when I use Chrome. The native Mail app opens to write a new email, but then I still have a blank tab open with the `mailto:` URL in the address bar, and the title: "Untitled".

I think removing the `target="_blank"` should be fine for all cases, any browser will always open a new window or popup by itself.

**Comment by billyquick** [comment] 2016-08-02 22:05
I see. I agree, that seems like it should work.

**Comment by XhmikosR** [comment] 2016-08-04 11:42
Duplicate of #26.

**Comment by mxstbr** [comment] 2016-08-04 12:13
Thanks @XhmikosR, also fixed thanks to @pavelkomiagin in #36! 🎉

**Closed as completed by mxstbr** 2016-08-04 12:13 UTC
